# This is a basic workflow to automatically build a Svelte app and deploy it to GitHub Pages

name: Deploy to Remote Server

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          key: ${{ secrets.SSHKEY }}
          debug: true
          script: cd /opt/la-movement-directory-web && git pull && /root/.nvm/versions/node/v20.5.1/bin/npm install && /root/.nvm/versions/node/v20.5.1/bin/npm run build && systemctl restart ladirectoryfrontend